import { EmissionFactor, TransportMode, WasteTreatment } from './types'

export const TRANSPORT_FACTORS: Record<TransportMode, EmissionFactor> = {
  twoWheeler: { id: 'india-two-wheeler-lca-2023', category: 'transportation', value: 0.1609, unit: 'kg CO2e/passenger-km', source: 'Life-cycle assessment of passenger transport: An Indian case study', sourceOrganization: 'International Transport Forum / OECD', version: '2023 publication', reportingYear: '2023', geography: 'India', methodology: 'Life-cycle passenger transport assessment', notes: 'Two-wheeler factor supplied for this calculator.' },
  car: { id: 'india-car-lca-2023', category: 'transportation', value: 0.3591, unit: 'kg CO2e/passenger-km', source: 'Life-cycle assessment of passenger transport: An Indian case study', sourceOrganization: 'International Transport Forum / OECD', version: '2023 publication', reportingYear: '2023', geography: 'India', methodology: 'Life-cycle passenger transport assessment', notes: 'Car factor supplied for this calculator.' },
  bus: { id: 'india-bus-lca-2023', category: 'transportation', value: 0.0315, unit: 'kg CO2e/passenger-km', source: 'Life-cycle assessment of passenger transport: An Indian case study', sourceOrganization: 'International Transport Forum / OECD', version: '2023 publication', reportingYear: '2023', geography: 'India', methodology: 'Life-cycle passenger transport assessment', notes: 'Bus factor supplied for this calculator.' },
  train: { id: 'india-train-passenger-km-older', category: 'transportation', value: 0.007837, unit: 'kg CO2/passenger-km', source: 'Indian Railways / Planning Commission-referenced non-suburban passenger-km factor', sourceOrganization: 'Indian Railways / Planning Commission', version: 'Older reference value', reportingYear: 'Not specified', geography: 'India', methodology: 'Non-suburban passenger-km operational reference', notes: 'Older CO2 reference value; reported separately from the 2023 life-cycle factors.' },
}

export const ELECTRICITY_FACTOR: EmissionFactor = { id: 'india-cea-electricity-fy-2024-25', category: 'electricity', value: 0.7117, unit: 'kg CO2/kWh', source: 'CO2 Baseline Database for the Indian Power Sector', sourceOrganization: 'Central Electricity Authority', version: '21.0', reportingYear: 'FY 2024-25', geography: 'India', methodology: 'CEA grid emission baseline database', notes: 'The calculator retains the supplied 0.7117 kg CO2/kWh precision for calculations.' }

export const WASTE_FACTORS: Record<WasteTreatment, EmissionFactor> = {
  composting: { id: 'india-organic-waste-composting', category: 'waste', value: 0.32, unit: 'kg CO2e/kg waste', source: 'Low Carbon Lifestyles material', sourceOrganization: 'Ministry of Environment, Forest and Climate Change, Government of India', version: 'Not specified', reportingYear: 'Not specified', geography: 'India', methodology: 'Organic waste treatment factor', notes: 'Applies to organic waste sent to composting.' },
  landfill: { id: 'india-organic-waste-landfill', category: 'waste', value: 1.29, unit: 'kg CO2e/kg waste', source: 'Low Carbon Lifestyles material', sourceOrganization: 'Ministry of Environment, Forest and Climate Change, Government of India', version: 'Not specified', reportingYear: 'Not specified', geography: 'India', methodology: 'Organic waste treatment factor', notes: 'Applies to organic waste sent to landfill.' },
}
